In [1]:
import os.path

import h5py
import numpy as np
import pandas as pd
import yaml

In [2]:
# load data from image files according the the yaml file
path = ["..","..","run_data","2023_11_17"]

run_data = yaml.safe_load(open(os.path.join(*path, "data.yml")))

In [3]:
run_data = pd.DataFrame(run_data)
run_data

ICT1  \
0   [0.7838166769, 1.5517169497, 0.6660754841, 0.9...   
1   [0.7684783271, 1.0617672532, 0.5376477788, 0.5...   
2   [0.0001273654, 0.3526255719, 2.803947332, 1.32...   
3   [0.4571668311, 0.2733020405, 0.6311303826, 0.6...   
4   [1.2932652314, 2.4160445273, -0.8038342866, 1....   
5   [0.901746513, -0.0530499038, -0.4178107182, 1....   
6   [1.0379599455, 2.4806796812, 0.3008228693, 0.4...   
7   [0.1503048232, 0.5389651321, -0.3269337565, -0...   
8   [1.9722026989, 0.8954513588, 1.1135891975, -0....   
9   [0.6616211687, 1.4951321403, 1.0691179536, 1.9...   
10  [1.1748171105, 2.1251796501, 1.9455701131, 0.8...   
11  [-0.777865437, 0.6748769792, 0.9436596977, 1.0...   
12  [1.9559144877, 1.0451199994, 1.8446140028, 1.7...   
13  [2.3991909064, 0.8849060098, 0.2318947175, -0....   
14  [1.8843370469, 0.173395374, 0.7957954193, -0.0...   
15  [0.6926502233, 2.3543759447, -0.5859797539, -0...   
16  [1.6158426289, 2.1083158831, 1.1438740525, 0.1...   
17  [0.3771303779, 0.573455148, 0.9665985662, 2.13...   
18  [-0.7886866752, 1.8030158005, 0.3202058706, 0....   
19  [1.1043927717, 1.8206347284, 0.9060423073, -0....   

                                                 ICT2  dipole_name  \
0   [2.8015550985, 0.5212906681, 1.3899855147, 1.6...            0   
1   [1.3675146913, -0.1321943202, 2.2807220533, 0....            0   
2   [0.8041859445, 1.2927583523, -0.0174525314, 0....            0   
3   [0.0531736984, 0.4025567406, 1.9052175532, 1.0...            0   
4   [1.6018678838, 1.0917308403, -0.4634930387, 0....            0   
5   [-0.7864953553, -0.7296902292, 0.5766898133, 0...            0   
6   [1.9365227743, 0.9438823397, 2.366485921, 2.86...            0   
7   [1.1585344888, 0.2742415762, 1.3808913186, 3.1...            0   
8   [1.4232358608, -0.3376332235, 2.1897538626, 0....            0   
9   [0.5622942192, 0.6000746138, 1.4105023892, 0.9...            0   
10  [1.5485105127, 2.2872738741, 0.7380720886, 0.8...            2   
11  [1.0796872891, -1.6146836255, 0.6224252229, 1....            2   
12  [-0.3995042993, 0.3257019259, 1.6656060008, 2....            2   
13  [1.5545972327, 2.2386054032, 1.6019435501, 0.6...            2   
14  [3.7290356014, 1.899014628, -0.4009493852, 1.0...            2   
15  [0.7408080127, 0.5548522017, -0.6135958617, 1....            2   
16  [0.4737855221, 3.356273913, 0.5363288288, 1.63...            2   
17  [1.5183387042, 1.4754486773, 0.8181600891, 1.0...            2   
18  [-0.3283855664, 0.4952256193, 1.54225986, 0.42...            2   
19  [0.1349427903, 1.6368254697, 0.5150565055, 0.8...            2   

    quad_pv_name                                save_filename  tdc_name  
0            0.0  ../run_data/2023_11_17/13ARV1_1700252901.h5         0  
1            2.5  ../run_data/2023_11_17/13ARV1_1700252914.h5         0  
2            5.0  ../run_data/2023_11_17/13ARV1_1700252926.h5         0  
3            7.5  ../run_data/2023_11_17/13ARV1_1700252939.h5         0  
4           10.0  ../run_data/2023_11_17/13ARV1_1700252952.h5         0  
5            0.0  ../run_data/2023_11_17/13ARV1_1700252964.h5         1  
6            2.5  ../run_data/2023_11_17/13ARV1_1700252977.h5         1  
7            5.0  ../run_data/2023_11_17/13ARV1_1700252990.h5         1  
8            7.5  ../run_data/2023_11_17/13ARV1_1700253002.h5         1  
9           10.0  ../run_data/2023_11_17/13ARV1_1700253015.h5         1  
10           0.0  ../run_data/2023_11_17/13ARV1_1700253028.h5         0  
11           2.5  ../run_data/2023_11_17/13ARV1_1700253040.h5         0  
12           5.0  ../run_data/2023_11_17/13ARV1_1700253053.h5         0  
13           7.5  ../run_data/2023_11_17/13ARV1_1700253066.h5         0  
14          10.0  ../run_data/2023_11_17/13ARV1_1700253078.h5         0  
15           0.0  ../run_data/2023_11_17/13ARV1_1700253091.h5         1  
16           2.5  ../run_data/2023_11_17/13ARV1_1700253104.h5         1  
17           5.0  ../run_data/2023_11_17/13ARV1_

In [4]:
# create a pivot table out of the data to collect settings
pivot_data = pd.pivot(
    run_data, index=["tdc_name", "dipole_name"],
    columns="quad_pv_name",
    values="save_filename"
)

In [5]:
# get numpy values in the correct shape
num_rows, num_cols = pivot_data.shape

fnames = pivot_data.values.reshape(2,2,5)

In [6]:
# create function to get data from h5 files
import numpy as np
def read_file(fname):
    with h5py.File(fname) as f:
        data_x = np.array((
            f["images"].attrs["quad_pv_name"],
            f["images"].attrs["tdc_name"],
            f["images"].attrs["dipole_name"],
        ))
        images = f["images"][:]

    return data_x, images

In [7]:
train_x = []
train_y = []
for i in range(len(fnames)):
    tx = []
    ty = []
    for j in range(len(fnames[0])):
        ttx = []
        tty = []
        for k in range(len(fnames[0,0])):
            data_x, images = read_file("../"+fnames[i,j,k])

            print(data_x)
            print(images.shape)

            ttx += [data_x]
            tty += [images]

        tx += [ttx]
        ty += [tty]

    train_x += [tx]
    train_y += [ty]

train_x = np.array(train_x).transpose([2,0,1,3])
train_y = np.array(train_y).transpose([2,0,1,3,4,5])

##
# params: [number of quad strengths, number of tdc voltages (2, off/on), number of dipole angles (2, off/on), number of scanning elements (3) ]
# images: [number of quad strengths, number of tdc voltages (2, off/on), number of
# dipole angles (2, off/on), number of images per parameter configuration, width in pixels, height in pixels]

[0. 0. 0.]
(10, 2000, 2000)
[2.5 0.  0. ]
(10, 2000, 2000)
[5. 0. 0.]
(10, 2000, 2000)
[7.5 0.  0. ]
(10, 2000, 2000)
[10.  0.  0.]
(10, 2000, 2000)
[0. 0. 2.]
(10, 2000, 2000)
[2.5 0.  2. ]
(10, 2000, 2000)
[5. 0. 2.]
(10, 2000, 2000)
[7.5 0.  2. ]
(10, 2000, 2000)
[10.  0.  2.]
(10, 2000, 2000)
[0. 1. 0.]
(10, 2000, 2000)
[2.5 1.  0. ]
(10, 2000, 2000)
[5. 1. 0.]
(10, 2000, 2000)
[7.5 1.  0. ]
(10, 2000, 2000)
[10.  1.  0.]
(10, 2000, 2000)
[0. 1. 2.]
(10, 2000, 2000)
[2.5 1.  2. ]
(10, 2000, 2000)
[5. 1. 2.]
(10, 2000, 2000)
[7.5 1.  2. ]
(10, 2000, 2000)
[10.  1.  2.]
(10, 2000, 2000)


In [8]:
train_x.shape

(5, 2, 2, 3)

In [9]:
train_y.shape


(5, 2, 2, 10, 2000, 2000)

In [10]:
train_x[0]

array([[[0., 0., 0.],
        [0., 0., 2.]],

       [[0., 1., 0.],
        [0., 1., 2.]]])