In [1]:
import os.path

import h5py
import pandas as pd
import yaml

In [2]:
# load data from image files according the the yaml file
path = "/home/awa/awa_data/12-05_6DReconstruction/"

run_data = yaml.safe_load(open(os.path.join(path, "reconstruction_scan/data.yml")))

In [3]:
quad_pv_name = "AWA:Bira3Ctrl:Ch10"
tdc_pv_name = "pi:QBCR1:Ch7:EnablePulse"
dipole_pv_name = "AWA:Bira4Ctrl:Ch01"

In [4]:
run_data = pd.DataFrame(run_data)
run_data

AWA:Bira3Ctrl:Ch10  AWA:Bira4Ctrl:Ch01   
0                 -1.0                0.00  \
1                 -0.5                0.00   
2                  0.0                0.00   
3                  0.5                0.00   
4                  1.0                0.00   
5                 -1.0                0.00   
6                 -0.5                0.00   
7                  0.0                0.00   
8                  0.5                0.00   
9                  1.0                0.00   
10                -1.0               -5.63   
11                -0.5               -5.63   
12                 0.0               -5.63   
13                 0.5               -5.63   
14                 1.0               -5.63   
15                -1.0               -5.63   
16                -0.5               -5.63   
17                 0.0               -5.63   
18                 0.5               -5.63   
19                 1.0               -5.63   

                                  AWAVXI11ICT:Ch4  pi:QBCR1:Ch7:EnablePulse   
0   [1.3e-09, 1.1e-09, 1.1e-09, 1.3e-09, 1.2e-09]                         0  \
1   [1.3e-09, 1.2e-09, 1.2e-09, 1.3e-09, 1.3e-09]                         0   
2   [1.3e-09, 1.3e-09, 1.3e-09, 1.2e-09, 1.3e-09]                         0   
3   [1.1e-09, 1.2e-09, 1.3e-09, 1.1e-09, 1.1e-09]                         0   
4   [1.1e-09, 1.1e-09, 1.1e-09, 1.2e-09, 1.2e-09]                         0   
5   [1.2e-09, 1.3e-09, 1.2e-09, 1.2e-09, 1.3e-09]                         1   
6   [1.2e-09, 1.1e-09, 1.3e-09, 1.1e-09, 1.2e-09]                         1   
7   [1.2e-09, 1.3e-09, 1.2e-09, 1.3e-09, 1.2e-09]                         1   
8   [1.1e-09, 1.3e-09, 1.1e-09, 1.2e-09, 1.3e-09]                         1   
9   [1.3e-09, 1.2e-09, 1.3e-09, 1.1e-09, 1.2e-09]                         1   
10  [1.2e-09, 1.2e-09, 1.2e-09, 1.1e-09, 1.3e-09]                         0   
11  [1.2e-09, 1.3e-09, 1.1e-09, 1.2e-09, 1.2e-09]                         0   
12  [1.3e-09, 1.3e-09, 1.3e-09, 1.2e-09, 1.2e-09]                         0   
13  [1.1e-09, 1.3e-09, 1.1e-09, 1.1e-09, 1.2e-09]                         0   
14  [1.2e-09, 1.2e-09, 1.1e-09, 1.1e-09, 1.3e-09]                         0   
15  [1.2e-09, 1.1e-09, 1.3e-09, 1.1e-09, 1.3e-09]                         1   
16  [1.2e-09, 1.3e-09, 1.2e-09, 1.1e-09, 1.3e-09]                         1   
17  [1.3e-09, 1.2e-09, 1.2e-09, 1.2e-09, 1.2e-09]                         1   
18  [1.2e-09, 1.3e-09, 1.1e-09, 1.3e-09, 1.1e-09]                         1   
19  [1.2e-09, 1.3e-09, 1.3e-09, 1.1e-09, 1.3e-09]                         1   

                                        save_filename  
0   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
1   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
2   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
3   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
4   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
5   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
6   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
7   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
8   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
9   /home/awa/awa_data/12-05_6DReconstruction/13AR...  
10  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
11  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
12  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
13  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
14  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
15  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
16  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
17  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
18  /home/awa/awa_data/12-05_6DReconstruction/13AR...  
19  /home/awa/awa_data/12-05_6DReconstruction/13AR...

In [5]:
# create a pivot table out of the data to collect settings
pivot_data = pd.pivot(
    run_data, index=[tdc_pv_name, dipole_pv_name],
    columns=quad_pv_name,
    values="save_filename"
)

In [6]:
# get numpy values in the correct shape
num_rows, num_cols = pivot_data.shape

fnames = pivot_data.values.reshape(2,2,5)

In [7]:
# create function to get data from h5 files
import numpy as np
def read_file(fname):
    with h5py.File(fname) as f:
        data_x = np.array((
            f["images"].attrs[quad_pv_name],
            f["images"].attrs[tdc_pv_name],
            f["images"].attrs[dipole_pv_name],
        ))
        images = f["images"][:]

    return data_x, images

In [ ]:
p0c = 62.0e6 # design momentum eV/c
C_LIGHT = 299792458
TDC_V = 3.7e6 # need to double check this value // verify calibration value
BEND_G = 20.0*3.1416/180.0/0.3018 # double check 0.3018 value
BEND_ON_PV_VALUE = -5.63 # double check
def quad_pv_to_k(quad_pv_value, p0c):
    gradient = quad_pv_value*100*1.32e-2/1.29*1.04
    beam_rigidity = p0c / C_LIGHT
    return gradient / beam_rigidity

def tdc_pv_to_v(tdc_pv_value):
    if tdc_pv_value == 0:
        return 0
    elif tdc_pv_value == 1:
        return TDC_V
    else: 
        raise ValueError("TDC PV value must be 0 or 1")
    
def bend_pv_to_g(bend_pv_value):
    if bend_pv_value == 0:
        return 2.22e-16 #machine epsilon for differentiability
    elif bend_pv_value == BEND_ON_PV_VALUE:
        return BEND_G
    else:
        raise ValueError("BEND PV value must be 0 or {}".format(BEND_ON_PV_VALUE))

In [7]:
train_x = []
train_x_physical_units = []
train_y = []
for i in range(len(fnames)):
    tx = []
    txp = []
    ty = []
    for j in range(len(fnames[0])):
        ttx = []
        ttxp = []
        tty = []
        for k in range(len(fnames[0,0])):
            fname_list = os.path.split(fnames[i,j,k])
            fname_list = list(fname_list[:-1]) + ["reconstruction_scan", fname_list[-1]]
            fname = os.path.join(*fname_list)
            
            data_x, images = read_file(fname)

            print(data_x)
            k = quad_pv_to_k(data_x[0])
            v = tdc_pv_to_v(data_x[1])
            g = bend_pv_to_g(data_x[2])
            data_x_physical_units = [k, v, g]
            print(data_x_physical_units)
            print(images.shape)

            ttx += [data_x]
            ttxp += [data_x_physical_units]
            tty += [images]

        tx += [ttx]
        txp += [ttxp]
        ty += [tty]

    train_x += [tx]
    train_x_physical_units += [txp]
    train_y += [ty]

train_x = np.array(train_x).transpose([2,0,1,3])
train_x_physical_units = np.array(train_x_physical_units).transpose([2,0,1,3])
train_y = np.array(train_y).transpose([2,0,1,3,4,5])

##
# params: [number of quad strengths, number of tdc voltages (2, off/on), number of dipole angles (2, off/on),
# number of scanning elements (3)]
# images: [number of quad strengths, number of tdc voltages (2, off/on), number of
# dipole angles (2, off/on), number of images per parameter configuration, width in pixels, height in pixels]

[-1.    0.   -5.63]
(5, 700, 700)
[-0.5   0.   -5.63]
(5, 700, 700)
[ 0.    0.   -5.63]
(5, 700, 700)
[ 0.5   0.   -5.63]
(5, 700, 700)
[ 1.    0.   -5.63]
(5, 700, 700)
[-1.  0.  0.]
(5, 700, 700)
[-0.5  0.   0. ]
(5, 700, 700)
[0. 0. 0.]
(5, 700, 700)
[0.5 0.  0. ]
(5, 700, 700)
[1. 0. 0.]
(5, 700, 700)
[-1.    1.   -5.63]
(5, 700, 700)
[-0.5   1.   -5.63]
(5, 700, 700)
[ 0.    1.   -5.63]
(5, 700, 700)
[ 0.5   1.   -5.63]
(5, 700, 700)
[ 1.    1.   -5.63]
(5, 700, 700)
[-1.  1.  0.]
(5, 700, 700)
[-0.5  1.   0. ]
(5, 700, 700)
[0. 1. 0.]
(5, 700, 700)
[0.5 1.  0. ]
(5, 700, 700)
[1. 1. 0.]
(5, 700, 700)


In [13]:
train_x.shape

(5, 2, 2, 3)

In [ ]:
train_x_physical_units.shape

In [9]:
train_y.shape


(5, 2, 2, 5, 700, 700)

In [15]:
train_x[0]

array([[[-1.  ,  0.  , -5.63],
        [-1.  ,  0.  ,  0.  ]],

       [[-1.  ,  1.  , -5.63],
        [-1.  ,  1.  ,  0.  ]]])