In [1]:
import os.path

import h5py
import pandas as pd
import yaml

In [2]:
# load data from image files according the the yaml file
path = ["..","..","run_data","2023_11_17"]

run_data = yaml.safe_load(open(os.path.join(*path, "data.yml")))

In [3]:
run_data = pd.DataFrame(run_data)
run_data

ICT1  \
0   [0.9685895525, 0.9275407734, 0.9227464728, 1.0...   
1   [1.0386552651, 0.9595960648, 0.9009403263, 0.9...   
2   [0.9575771563, 1.0550407668, 0.9911021657, 0.9...   
3   [0.9754499864, 1.0685999139, 1.0424194168, 0.9...   
4   [0.9641839214, 1.0028211861, 0.9202209618, 1.0...   
5   [0.9845524484, 0.9159889088, 0.9463392509, 0.9...   
6   [0.9260447723, 0.9442116863, 1.0852642445, 0.9...   
7   [1.0097759096, 1.0452899895, 1.041574279, 1.01...   
8   [0.9642815874, 1.0737504077, 0.9136486462, 1.0...   
9   [1.0041341996, 0.997799832, 0.9456453785, 1.06...   
10  [0.9186706868, 1.0282447005, 1.0681298456, 1.0...   
11  [0.9705376773, 0.9690864938, 0.9652185509, 0.9...   
12  [0.902358747, 1.0875911019, 0.9757387493, 1.04...   
13  [1.0155899574, 0.9680754644, 1.0282553553, 1.0...   
14  [0.9767273878, 0.9770921672, 0.9801624768, 1.0...   
15  [0.9763385157, 1.0490945286, 1.0620876544, 0.9...   
16  [0.9456961454, 1.0908944932, 1.0375948302, 0.9...   
17  [1.0229787302, 0.9826408911, 1.0570604958, 1.0...   
18  [0.9995078238, 0.9473672119, 0.9023716457, 1.0...   
19  [1.0822706827, 1.0631325454, 0.9036863362, 0.9...   

                                                 ICT2  dipole_name  \
0   [1.0794398194, 1.0766765703, 1.064339215, 1.18...            0   
1   [0.8815740854, 1.1187479521, 0.8820179623, 0.9...            0   
2   [0.9897631782, 0.9026718179, 0.9613517121, 0.9...            0   
3   [1.0082677283, 1.0056026229, 0.9788066444, 1.1...            0   
4   [1.0924266447, 1.1035695579, 0.9492391804, 0.9...            0   
5   [1.0172486335, 1.0470616554, 0.9528940276, 0.9...            0   
6   [0.8998327749, 0.9407936466, 0.9652159014, 1.2...            0   
7   [1.0678310221, 0.9919742227, 0.9988086481, 1.0...            0   
8   [0.8777402427, 0.9402199595, 0.9244413054, 0.9...            0   
9   [1.0395839434, 1.0899779246, 1.0193278183, 0.9...            0   
10  [1.0516995135, 0.8781198488, 1.0363638618, 0.9...            2   
11  [1.0985044317, 1.0579951503, 1.0528335551, 0.8...            2   
12  [0.9039003377, 0.9014520679, 0.9597465399, 1.1...            2   
13  [0.8463612995, 1.0759848066, 0.9547521872, 1.1...            2   
14  [1.0024033996, 0.8870199969, 1.0571616699, 0.9...            2   
15  [0.8352380666, 0.9208155883, 1.1666813945, 1.0...            2   
16  [1.0687179018, 1.044436791, 1.0153137419, 0.74...            2   
17  [0.9324282481, 0.873557955, 0.9322048257, 1.07...            2   
18  [0.9846366492, 0.9720527419, 0.8652048771, 1.0...            2   
19  [1.0193346402, 1.1242536839, 0.8810780321, 1.1...            2   

    quad_pv_name                                save_filename  tdc_name  
0            0.0  ../run_data/2023_11_17/13ARV1_1701286176.h5         0  
1            2.5  ../run_data/2023_11_17/13ARV1_1701286193.h5         0  
2            5.0  ../run_data/2023_11_17/13ARV1_1701286211.h5         0  
3            7.5  ../run_data/2023_11_17/13ARV1_1701286225.h5         0  
4           10.0  ../run_data/2023_11_17/13ARV1_1701286243.h5         0  
5            0.0  ../run_data/2023_11_17/13ARV1_1701286256.h5         1  
6            2.5  ../run_data/2023_11_17/13ARV1_1701286272.h5         1  
7            5.0  ../run_data/2023_11_17/13ARV1_1701286289.h5         1  
8            7.5  ../run_data/2023_11_17/13ARV1_1701286309.h5         1  
9           10.0  ../run_data/2023_11_17/13ARV1_1701286324.h5         1  
10           0.0  ../run_data/2023_11_17/13ARV1_1701286347.h5         0  
11           2.5  ../run_data/2023_11_17/13ARV1_1701286364.h5         0  
12           5.0  ../run_data/2023_11_17/13ARV1_1701286380.h5         0  
13           7.5  ../run_data/2023_11_17/13ARV1_1701286397.h5         0  
14          10.0  ../run_data/2023_11_17/13ARV1_1701286411.h5         0  
15           0.0  ../run_data/2023_11_17/13ARV1_1701286429.h5         1  
16           2.5  ../run_data/2023_11_17/13ARV1_1701286448.h5         1  
17           5.0  ../run_data/2023_11_17/13ARV1_

In [4]:
# create a pivot table out of the data to collect settings
pivot_data = pd.pivot(
    run_data, index=["tdc_name", "dipole_name"],
    columns="quad_pv_name",
    values="save_filename"
)

In [5]:
# get numpy values in the correct shape
num_rows, num_cols = pivot_data.shape

fnames = pivot_data.values.reshape(2,2,5)

In [6]:
# create function to get data from h5 files
import numpy as np
def read_file(fname):
    with h5py.File(fname) as f:
        data_x = np.array((
            f["images"].attrs["quad_pv_name"],
            f["images"].attrs["tdc_name"],
            f["images"].attrs["dipole_name"],
        ))
        images = f["images"][:]

    return data_x, images

In [7]:
train_x = []
train_y = []
for i in range(len(fnames)):
    tx = []
    ty = []
    for j in range(len(fnames[0])):
        ttx = []
        tty = []
        for k in range(len(fnames[0,0])):
            data_x, images = read_file("../"+fnames[i,j,k])

            print(data_x)
            print(images.shape)

            ttx += [data_x]
            tty += [images]

        tx += [ttx]
        ty += [tty]

    train_x += [tx]
    train_y += [ty]

train_x = np.array(train_x).transpose([2,0,1,3])
train_y = np.array(train_y).transpose([2,0,1,3,4,5])

##
# params: [number of quad strengths, number of tdc voltages (2, off/on), number of dipole angles (2, off/on),
# number of scanning elements (3)]
# images: [number of quad strengths, number of tdc voltages (2, off/on), number of
# dipole angles (2, off/on), number of images per parameter configuration, width in pixels, height in pixels]

[0. 0. 0.]
(10, 2000, 2000)
[2.5 0.  0. ]
(10, 2000, 2000)
[5. 0. 0.]
(10, 2000, 2000)
[7.5 0.  0. ]
(10, 2000, 2000)
[10.  0.  0.]
(10, 2000, 2000)
[0. 0. 2.]
(10, 2000, 2000)
[2.5 0.  2. ]
(10, 2000, 2000)
[5. 0. 2.]
(10, 2000, 2000)
[7.5 0.  2. ]
(10, 2000, 2000)
[10.  0.  2.]
(10, 2000, 2000)
[0. 1. 0.]
(10, 2000, 2000)
[2.5 1.  0. ]
(10, 2000, 2000)
[5. 1. 0.]
(10, 2000, 2000)
[7.5 1.  0. ]
(10, 2000, 2000)
[10.  1.  0.]
(10, 2000, 2000)
[0. 1. 2.]
(10, 2000, 2000)
[2.5 1.  2. ]
(10, 2000, 2000)
[5. 1. 2.]
(10, 2000, 2000)
[7.5 1.  2. ]
(10, 2000, 2000)
[10.  1.  2.]
(10, 2000, 2000)


In [8]:
train_x.shape

(5, 2, 2, 3)

In [9]:
train_y.shape


(5, 2, 2, 10, 2000, 2000)

In [10]:
train_x[0]

array([[[0., 0., 0.],
        [0., 0., 2.]],

       [[0., 1., 0.],
        [0., 1., 2.]]])